# Generated by Django 4.2.13 on 2024-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('company_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('lead', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='cold', max_length=10)),
                ('related_name', models.CharField(max_length=40)),
                ('linkedin_connection', models.CharField(max_length=50)),
                ('comments', models.TextField(max_length=300)),
                ('first_contact', models.DateTimeField(verbose_name='date of first contact')),
                ('description_contact', models.TextField(max_length=200)),
                ('date_of_last_contact', models.DateTimeField(verbose_name='date of last contact')),
                ('description_contact_more', models.TextField(max_length=300)),
                ('follow_up_action', models.CharField(max_length=100)),
                ('date_of_next_contact', models.DateTimeField(verbose_name='date of next contact')),
                ('new_business', models.TextField(max_length=500)),
                ('recommendation', models.TextField(max_length=500)),
            ],
        ),
    ]
