# Generated by Django 4.2.13 on 2024-07-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_last_contact',
            field=models.DateTimeField(blank=True, verbose_name='date of last contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_next_contact',
            field=models.DateTimeField(blank=True, verbose_name='date of next contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description_contact_more',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_contact',
            field=models.DateTimeField(blank=True, verbose_name='date of first contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='follow_up_action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='lead',
            field=models.CharField(blank=True, choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='cold', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='linkedin_connection',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='new_business',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='recommendation',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='related_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
