# Generated by Django 4.2.13 on 2024-07-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_last_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of last contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_next_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of next contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description_contact',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='description_contact_more',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of first contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='follow_up_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lead',
            field=models.CharField(blank=True, choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='cold', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='linkedin_connection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='new_business',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='recommendation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='related_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
